name: liquid_snap_glass
description: The Ultimate High-Performance Liquid Glass Video Downloader.
publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Visuals
  glass_kit: ^3.0.0
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  
  # Networking
  http: ^1.2.1
  dio: ^5.4.3
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.6

  # Utilities
  provider: ^6.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  intl: ^0.19.0           # Fix for date crash
  collection: ^1.18.0     # Fix for list crash
  
  # File System
  open_filex: ^4.4.0
  flutter_local_notifications: ^17.1.0
  gallery_saver: ^2.3.2

dependency_overrides:
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ⚠️ تم تعطيل هذا الجزء مؤقتاً لحل مشكلة Build Error
  # لازم تنشئ المجلدات دي وترفع فيها صور عشان تشيل الـ #
  # assets:
  #   - assets/images/
  #   - assets/icons/
